### ISSUE TITLE
Add setting: after viewing a blob, auto-delete files?

### ISSUE THREAD

**Issue by tscv11** [tscv11/leo4sqlite#4]
Another one that explains itself. The problem is that I don't know if this feature is a good idea. (Automatically deleting files is always at least a little bit 'iffy', even if it's just an option). Input welcome!

**Comment by tbnorth** [comment]
This is tricky because it's hard to know when the viewrender pane is "done".  In the current setup the user usually "hides" it rather than closes it, so if they later unhide it, they could expect to see the content it had when they hid it.  For some content types I suspect this would be problematic if the extracted file was deleted already.

Perhaps the simplest solution is to defer deleting extracted files until Leo is closed.  

More complicated alternatives would be (a) doing it when the pane is closed/hidden, and in the case of it being hidden, resetting it to a plain text view, or (b) adding a hook to viewrendered to allow actions to be called when the pane's content changes.

Aside: Ideally the extracted files should always be extracted under the same name, so if the user views the same 20 Mb movie twenty times, there aren't 20 copies of it.

**Comment by tbnorth** [comment]
In this snippet:
```python
from leo.core.leoQt import QtWidgets
vr = c.frame.top.findChild(QtWidgets.QWidget, 'viewrendered_pane')
if vr:
    w = vr.ensure_text_widget()
    vr.set_html("Inactive view pane", w)
    vr.hide()
```
the two lines mentioning `w` ensure the vr pane's no longer showing your blob content.

**Comment by tscv11** [comment]
This feature has been added to the script and the docstring has been updated to reflect that fact.
